// npm install tailwindcss @tailwindcss/vite

// import { defineConfig } from 'vite'
// import tailwindcss from '@tailwindcss/vite'

// export default defineConfig({
//   plugins: [
//     tailwindcss(),
//   ],
// })
// @import "tailwindcss";

<FaRegBell />
<MdOutlineVideoCall  />
 <FaMicrophone/>
  <IoIosSearch size={"24px"} />
  <FiMenu
   <img src={"/logo.png"} alt="" className="w-28 cursor-pointer" />